export type Lab={slug:string;title:string;category:string;difficulty:'Easy'|'Medium'|'Hard'|'Insane';points:number;time:string;description:string;skills:string[];brief:string;objective:string;flag:string};
export const labs:Lab[]=[
{slug:'ghost-protocol',title:'Ghost Protocol',category:'Web',difficulty:'Easy',points:100,time:'20 min',description:'Map an intentionally vulnerable demo service and recover its training flag.',skills:['HTTP','Recon','Headers'],brief:'A forgotten staging service is leaking more metadata than its operator intended.',objective:'Inspect the simulated service evidence and identify the exposed training token.',flag:'SG{headers_tell_stories}'},
{slug:'broken-trust',title:'Broken Trust',category:'API',difficulty:'Medium',points:250,time:'45 min',description:'Trace an authorization failure through a synthetic multi-tenant API.',skills:['API','BOLA','JSON'],brief:'Tenant boundaries are inconsistent across two API resources.',objective:'Follow the provided request trail and recover the synthetic cross-tenant flag.',flag:'SG{objects_need_owners}'},
{slug:'phantom-packet',title:'Phantom Packet',category:'Network',difficulty:'Medium',points:300,time:'50 min',description:'Analyze a compact packet narrative and find the anomalous service.',skills:['TCP/IP','PCAP','DNS'],brief:'A lab subnet shows periodic traffic to a service nobody remembers deploying.',objective:'Correlate the simulated telemetry and identify the beacon marker.',flag:'SG{follow_the_beacon}'},
{slug:'memory-echo',title:'Memory Echo',category:'Forensics',difficulty:'Hard',points:500,time:'90 min',description:'Reconstruct an incident from process, shell, and filesystem artifacts.',skills:['Forensics','Linux','Timeline'],brief:'A disposable workstation was compromised during a controlled exercise.',objective:'Build the event sequence and recover the final exercise marker.',flag:'SG{timeline_beats_guessing}'},
{slug:'prompt-phantom',title:'Prompt Phantom',category:'AI Security',difficulty:'Hard',points:550,time:'75 min',description:'Audit a simulated agent boundary for unsafe tool-routing behavior.',skills:['AI','Prompt Injection','Tooling'],brief:'A synthetic support agent has access to mock internal tools and untrusted documents.',objective:'Find the boundary failure in the supplied transcript without targeting any real service.',flag:'SG{trust_boundaries_apply_to_agents}'},
{slug:'cipher-cellar',title:'Cipher Cellar',category:'Crypto',difficulty:'Insane',points:900,time:'120 min',description:'Untangle a deliberately flawed training cryptosystem.',skills:['Crypto','Encoding','Analysis'],brief:'An internal challenge author invented a protocol. Naturally, this went well.',objective:'Reason through the provided construction and recover the lab-only secret.',flag:'SG{dont_invent_crypto}'},
];
export const categories=['All','Web','API','Network','Forensics','AI Security','Crypto'];
