'use client';import Link from 'next/link';import {useEffect,useState} from 'react';import type {Lab} from '@/lib/labs';import {CheckCircle2,ChevronLeft,Flag,Terminal} from 'lucide-react';
export default function LabView({lab}:{lab:Lab}){const key='sg-solved-'+lab.slug;const [flag,setFlag]=useState('');const [msg,setMsg]=useState('');const [solved,setSolved]=useState(false);const [busy,setBusy]=useState(false);useEffect(()=>setSolved(localStorage.getItem(key)==='1'),[key]);async function submit(e:React.FormEvent){e.preventDefault();setBusy(true);setMsg('VERIFYING //');try{const r=await fetch('/api/flags',{method:'POST',headers:{'content-type':'application/json'},body:JSON.stringify({slug:lab.slug,flag})});const j=await r.json();if(j.ok){localStorage.setItem(key,'1');setSolved(true);setMsg('FLAG ACCEPTED // '+lab.points+' POINTS')}else setMsg('FLAG REJECTED // inspect the evidence and try again')}catch{setMsg('VALIDATOR OFFLINE // try again')}finally{setBusy(false)}}return <main className='labPage'><Link className='back' href='/#labs'><ChevronLeft size={16}/> RETURN TO RANGE</Link><div className='labHero'><span className='category'>{lab.category}</span><h1>{lab.title}</h1><p>{lab.description}</p><div className='skills'>{lab.skills.map(x=><span key={x}>{x}</span>)}</div></div><div className='labLayout'><section className='brief'><span className='kicker'>// MISSION BRIEF</span><h2>SCENARIO</h2><p>{lab.brief}</p><h2>OBJECTIVE</h2><p>{lab.objective}</p><div className='evidence'><Terminal/><div><b>ISOLATED TRAINING TARGET</b><code>{`$ range inspect ${lab.slug}
state: ready
network: isolated
ttl: 30m
external_targets: denied

$ mission
Use only SPECTER.GHOST training assets or systems you are authorized to test.`}</code></div></div></section><aside><div className='sidebox'><span>DIFFICULTY</span><b>{lab.difficulty}</b><span>REWARD</span><b>{lab.points} PTS</b><span>EST. TIME</span><b>{lab.time}</b></div><form className='flagbox' onSubmit={submit}><Flag/><b>SUBMIT FLAG</b><input value={flag} onChange={e=>setFlag(e.target.value)} placeholder='SG{...}' autoComplete='off'/><button disabled={busy}>{busy?'VERIFYING...':'VERIFY FLAG'}</button>{msg&&<p className={solved?'ok':''}>{solved&&<CheckCircle2 size={15}/>} {msg}</p>}</form></aside></div></main>}
